# Form implementation generated from reading ui file 'agentint.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 647)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 551, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(600, 190, 171, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boxesLabel = QtWidgets.QLabel(parent=self.widget)
        self.boxesLabel.setObjectName("boxesLabel")
        self.verticalLayout.addWidget(self.boxesLabel)
        self.goalLabel = QtWidgets.QLabel(parent=self.widget)
        self.goalLabel.setObjectName("goalLabel")
        self.verticalLayout.addWidget(self.goalLabel)
        self.scoreLabel = QtWidgets.QLabel(parent=self.widget)
        self.scoreLabel.setObjectName("scoreLabel")
        self.verticalLayout.addWidget(self.scoreLabel)
        self.restartButton = QtWidgets.QPushButton(parent=self.widget)
        self.restartButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.restartButton.setObjectName("restartButton")
        self.verticalLayout.addWidget(self.restartButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agent 007"))
        self.boxesLabel.setText(_translate("MainWindow", "Boxes:"))
        self.goalLabel.setText(_translate("MainWindow", "Goal:"))
        self.scoreLabel.setText(_translate("MainWindow", "Score:"))
        self.restartButton.setText(_translate("MainWindow", "Restart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
